### PR TITLE
add php_eol as line break

### PR DESCRIPTION
**Pull request by reinfi**
Solves https://github.com/cheeZery/depdoc/issues/7

I was not sure while the documentation is written after every package manager.

### CODE REVIEW

**Comment by cheeZery** [comment]
But instead we of course can merge this PR and @GodLesZ will figure our what to do with it, because those nasty fixed Windows-style line separators are really getting on my nerves ;-)

**Comment by reinfi** [comment]
I would prefer to merge this one as this behavior is really bad and not sure how long #8 would take.

But of course this is your decision :)

**Comment by GodLesZ** [comment]
@reinfi #12 is the future and ready to be merged ;)

**Comment by GodLesZ** [comment]
Can be closed now - sorry @reinfi for the waste of time :/

**Pull request closed without merging**
